### ISSUE TITLE
Implement node part

### ISSUE THREAD

**Issue by dfcreative** [audiojs/audio-decode#1]
Right now it is just a stub package for browser, using decodeAudioData.
The main and the most important part is make it work in node.

**Comment by jamen** [comment]
I think I almost have an implementation for mono channels, and those after wont be too hard.

But I'm trying to figure out how to convert the WAVE PCM data (from 0 to whatever the sample size is) to a `Float32Array`.  I don't know how `Float32Array`s work, is it `1` to `-1`?

**Comment by dfcreative** [comment]
Yep, exactly, `-1..1`. Basically you can look at [analyzer node](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatTimeDomainData)

**Comment by jamen** [comment]
Well, I got it to play something somewhat close, but it is louder and distorted and I cannot figure out why.

**Comment by dfcreative** [comment]
Maybe we should try to take [aurora](https://npmjs.org/package/av) lib to cover main codec cases straigh-ahead? I would also suggest mb try to use [wav-decoder](https://www.npmjs.com/package/wav-decoder), @mohayonao creates really good modules. Just to save time and later support headache, unless it is useful as experience etc.

**Comment by jamen** [comment]
Aurora sounds good.  What formats should we support with it?

**Comment by jamen** [comment]
It seems like there is a lot in aurora we might not need.  I think using decoders might be better.

**Comment by dfcreative** [comment]
Well I guess mp3, flac, wav and ogg are must-have

**Comment by dfcreative** [comment]
To note [audio-type](https://github.com/hemanth/audio-type)

**Comment by dfcreative** [comment]
Should we test js-impl or take https://www.npmjs.com/package/wav-decoder directly? I feel like very soon it might be needed in [audio](https://github.com/audiojs/audio), to work both in browser/node

**Comment by dfcreative** [comment]
I just released _wav-decoder_-based node part.  It is up to mp3, ogg etc decoders.

**Comment by dfcreative** [comment]
Also added _mp3_ decoder based on aurora

**Comment by dfcreative** [comment]
Ok, audio-decode@1.2.0 now able to do wav/mp3 and optional additional codecs.

**Comment by jamen** [comment]
Wow, awesome work.  :)

Sorry for being pretty slow, also gonna be a bit busy the following few days.  You are doing great job maintaining though, thanks. :D
