### ISSUE TITLE
Hangs on decoding local mp3

### ISSUE THREAD

**Issue by GeoffreyPlitt** [audiojs/audio-decode#19]
```const fs = require('fs')
const decode = require('audio-decode')

decode(fs.readFileSync('./path/to/song.mp3'))
.then(console.log)
.catch(console.error)
```

It hangs for me. How to trouble-shoot?

**Comment by Kefir100** [comment]
Encountered the same issue, but later found out that a tiny sample logs out just fine. Maybe it just takes time to process a large file.
