### ISSUE TITLE
Add stream version

### ISSUE THREAD

**Issue by dy** [audiojs/audio-decode#2]
`audio-decode/stream` should decode input pcm data by chunks, if it is possible, or as a single piece if not.
It is important to make it compatible with other stream-based components.

**Comment by publicocean0** [comment]
Cool..... 
For helping you i can tell you what i learnt about it.

 surely you need a demuxer/decoder for reading mp3 fields inside.
there are 2 ways for realizing it.
  1 using MSE ... for it is sufficient a demuxer for sending blocks with right aligments. It works just in chrome and asking on firefox team ... they wont to realize it. So it is not a practical way. 
 2 converting stream to pcm .... but for it you need a decoder. This solution will work in any modern browser. There is a problem ... you can find in github decoder for mp3 but they accept in input the entire file or you cant seek back in the file loading it. In aurora for example there is a mp3 decoder.... but contains bugs(you can find in the last issues one found by me) and it loads all the mp3 file in memory. In many mobile devices this solution create crashing for out of memory. Seek function works with some bugs just when all file is in memory. 
3. last solution is to embed the mp3 song in a mp4 container .. in this way using mse you can stream it in all browser except in ios safari. Anyway if you receve a mp3 file you are blocked.

**Comment by dy** [comment]
Next time.
