### ISSUE TITLE
Cannot decode mp3 Buffer

### ISSUE THREAD

**Issue by xorbis** [audiojs/audio-decode#21]
Receiving an MP3 buffer from Google Cloud Text-to-speech API and I cannot seem to be able to play it back.

```
		console.log("Synthesizing...");
		const [speech] = await this.client.synthesizeSpeech(request);
		console.log("Synthesized: ", speech);

		console.log("Decoding...");
		const audioBuffer = await decode(speech.audioContent);
		console.log(`Decoded: ${audioBuffer}`);

		console.log("Playing...");
		await play(audioBuffer, {
			autoplay: true,
		});
```
I get this error:
```
Synthesizing...
Synthesized:  { audioContent: <Buffer ff f3 44 c4 00 00 00 03 48 01 40 00 00 f0 1a 72 01 46 bc 0d 51 20 39 07 bc 63 44 a1 f8 1c 08 20 c3 df e0 6c 10 58 60 80 00 31 8f fc 03 46 18 5c 1b 16 ... > }
Decoding...
(node:4404) UnhandledPromiseRejectionWarning: Error: Cannot detect audio format of buffer
```

**Comment by xorbis** [comment]
The lena/mp3 example works and I can play back the mp3 if I write the buffer to disk as output.mp3 using ```fs.writeFileSync("output.mp3", speech.audioContent, "binary");```

**Comment by sokolas** [comment]
Can't decode the google tts mp3, too. Tried both the audio buffer and saving the mp3 file. The file can be played by VLC but can't be decoded with this library.

**Comment by dy** [comment]
Try again v2. Must work well.
