### ISSUE TITLE
I cannot import into my TypeScript based project

### ISSUE THREAD

**Issue by pschuster** [audiojs/audio-decode#29]
Hi, when adding that repo to my TypeScript based NodeJS server, I get this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/audio-decode/audio-decode.js from .../apps/backend/main.js not supported.
Instead change the require of audio-decode.js in .../apps/backend/main.js to a dynamic import() which is available in all CommonJS modules.
```

I tried all possible ways of importing the module, like this:

```
import * as decode from 'audio-decode';
import decode from 'audio-decode';
import {decodeAudio} from 'audio-decode';
```

I always get the same error.

My tsconfig.json looks like this:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["node"],
    "emitDecoratorMetadata": true,
    "target": "es2015"
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}
```

What can I do to use that package?

**Comment by dy** [comment]
Hi!. I understand your concern, but it seems TypeScript has own ideas about importing modules, honestly I'm not really aware of. This module supports standard ESM, the rest I can only leave up to consumers/implementors.
Not big proponent of typescript, if you or someone finds out the solution - we can merge it.

**Comment by pschuster** [comment]
I finally understood what is going on: I am working on NestJS, that is still in CommonJS mode. Audio decode just exports as ESM module. You cannot import ESM modules from CommonJS, but you can import CommonJS and ESM from ESM. As for me there is no option to move to ESM (NestJS does not allow that for now), I needed to find another solution. It's pretty simple, but requires your code to be in async (which is easily doable most of the time).

My code now looks like this:

```typescript
  private async getDecoder(): Promise<(buffer: Buffer) => Promise<any>> {
    const module = await (eval(`import('audio-decode')`) as Promise<any>);
    return module.default;
  }
```

The ugly `eval` way of doing it also imports types and other things into `global`, i.e. the local scope. If you just do the recommended way of what you see everywhere, it might not always work.

Then, in my function that wants to decode the audio file, I use it like this:

```typescript
  private async playSound(filePath: string) {
    const decode = await this.getDecoder();
    const audioBuffer = await decode(fs.readFileSync(filePath));
    //...
  }
```

@dy I noticed that you are actively working on your project (and I really like it), perhaps you'll invest an hour on also exporting CommonJS which would make life for everyone much easier to consume your great project. I found a great article on how to do that: https://antfu.me/posts/publish-esm-and-cjs.
