### ISSUE TITLE
`./browser.js` is mentioned in `package.json`, but there is no such a file

### ISSUE THREAD

**Issue by UlyssesZh** [audiojs/audio-decode#34]
`./browser.js` is mentioned in `package.json`, but there is no such a file:

https://github.com/audiojs/audio-decode/blob/83c3883f5a2505de50da880c7c58a516d4415793/package.json#L23C2-L23C2

This is fatally confusing build tools such as esinstall, which prevents this package from being live on [Skypack](https://skypack.dev), [UNPKG](https://unpkg.com), etc.

**Comment by dy** [comment]
Fixed in 2.1.4

**Comment by HalfWhitt** [comment]
Just came here from [this discussion](https://github.com/orgs/community/discussions/61499) about the permalink not embedding a code view. Just to confirm the feature is currently working: when I change the URL to `https://github.com/audiojs/audio-decode/blob/83c3883f5a2505de50da880c7c58a516d4415793/package.json#L23`, as suggested there, it works fine, at least as it renders for me.

https://github.com/audiojs/audio-decode/blob/83c3883f5a2505de50da880c7c58a516d4415793/package.json#L23

Screenshot of how it appears in my browser:

<img width="836" height="95" alt="Screenshot of code link" src="https://github.com/user-attachments/assets/8e6a5523-8ab3-4e3f-aff0-e0ee12bae964" />
