### ISSUE TITLE
Decoder requires an unload function

### ISSUE THREAD

**Issue by e-senturk** [audiojs/audio-decode#38]
Hi I am using this decoder and it works well overall. I have a minor issue when I change decoding types. If I use different decoder  decoder can't work stops working for certain file types. Until I reload the app. I thought unloading the resources but I didn't find this functionality.
 
Steps to reproduce the issue.
1-) Run decoder.flac() -> To load flac format.
2-) Run decoder.flac(flacFile) -> I decoded a flac file and it worked well
3-) Run decoder.mp3() -> It looks like working and loading mp3
4-) Run decoder.mp3(mp3File) -> Decoder crashes and not working gives this error in console.

Error:
DOMException: Failed to construct 'AudioBuffer': The number of frames provided (0) is less than or equal to the minimum bound (0).

If I only try to step 3 and 4 it successfuly encodes mp3 file. 

Thank you for this awesome library.

**Comment by dy** [comment]
Yeah, there was a typo. Please check again, it must work now.
