### ISSUE TITLE
Bump mpg123-decoder dependency to 1.x

### ISSUE THREAD

**Issue by UlyssesZh** [audiojs/audio-decode#39]
I am developing something that requires millisecond-level precision in audio synchronization, and I met with some issues in this aspect with MP3 format (I am aware that OGG and Opus are generally preferable than MP3 in this consideration, but the audio files that I deal with are user-uploaded). I found eshaz/wasm-audio-decoders#105, which fixed this problem, and it was released in mpg123-decoder version 1.0.0. I think audio-decode should bump that dependency version from ^0.4.10 to ^1.0.0 to include this important fix.

**Comment by dy** [comment]
Sure, done @UlyssesZh, thanks!
