### ISSUE TITLE
Must use import to load ES Module: audio-decode

### ISSUE THREAD

**Issue by 01JAMIL** [audiojs/audio-decode#40]
I encountered an error when trying to use the audio-decode package in my Node.js application. The error message states:

`Error: Must use import to load ES Module: D:\Freelance\Echo-ai\backend\node_modules\audio-decode\audio-decode.js`

**Comment by dy** [comment]
Likely you use CJS (require) to load the package. You need to use bundler for that purpose or latest node version. Or just switch your project to type="module" (ESM). Should help.
